# Comparación de Modelos Númericos con puntos alazar

A continución, se muestra la comparación de varios modelos númericos considerando 15 puntos alazar para las siguiente funciones:
- Función Esfera (10 variables)
- Función McCormick (2 variables)
- Función de Dixon-Price (4 variables)
- Función de Easom (2 variables)
- Función de Rastrigin (5 variables)

NOTA:
-  Las funciones y los modelos fueron implementados como modulos individuales para poder ser invocados desde el notebook

## Importación de Dependencias y Generación de puntos aleatorios

In [166]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [167]:
%autoreload 2

In [168]:
# Dependencias

import numpy as np
import random
from config.logging import setUpLogging
from graph.graph_foo import FunctionPlotter2D
from numerical_methods.gradient_descent import MDG_Wolfe
from numerical_methods.newton import NewtonMethod
from numerical_methods.max_decrease import MDG_DM
from functions.sphere_foo import SphereFunction
from functions.mcCormick_foo import McCormickFunction
from functions.dixon_price_foo import DixonPriceFunction
from functions.easom_foo import EasomFunction
from functions.rastrigin_foo import RastriginFunction
from utils.aux_functions import getTestValues, mergeLists, crear_tabla_comparativa, resumen_tabla
from graph.graph_foo import FunctionPlotter2D
import logging

setUpLogging()
logger = logging.getLogger(__name__)

# Cantidad de puntos
n_points = 15

# Función Esfera con 10 variables
sphere = SphereFunction()
test_data_sphere: np.array = getTestValues(n_points, 10, sphere.domain[0], sphere.domain[1])
print("Sphere Test Data: ", test_data_sphere)


# Función McCormick con 2 variables
mcCormick = McCormickFunction()

test_data_mcCormick_x0: np.array = getTestValues(n_points, 1, mcCormick.domain[0], mcCormick.domain[1])
test_data_mcCormick_x1: np.array = getTestValues(n_points, 1, mcCormick.domain_x2[0], mcCormick.domain_x2[1])
test_data_mcCormick: np.array[tuple] = mergeLists(test_data_mcCormick_x0, test_data_mcCormick_x1)
print("McCormick Test Data: ",test_data_mcCormick)

# Función de Dixon-Price con 4 variables
dixon_price = DixonPriceFunction()

test_data_dixon_price: np.array = getTestValues(n_points, 4, dixon_price.domain[0], dixon_price.domain[1])
print("Dixon-Price Test Data: ", test_data_dixon_price)

# Función de Easom con 2 variables
easom = EasomFunction()

test_data_easom: np.array = getTestValues(n_points, 2, easom.domain[0], easom.domain[1])
print("Easom Test Data: ", test_data_easom)

# Función de Rastrigin con 5 variables
rastrigin = RastriginFunction()

test_data_rastrigin: np.array = getTestValues(n_points, 5, rastrigin.domain[0], rastrigin.domain[1])
print("Rastrigin Test Data: ", test_data_rastrigin)

Sphere Test Data:  [[-8.27071677e-01  1.35268037e+00  4.79484706e-01  3.42358747e+00
   4.76951059e+00  2.11343386e+00  3.97407964e+00 -4.58287827e+00
  -3.01021865e+00 -2.22297965e+00]
 [-1.48061601e-01  5.76938089e-01  2.25146783e+00  1.82342141e-01
   3.98317049e+00  1.15572064e+00  1.99916449e-01 -3.78133191e+00
  -3.97722024e+00 -2.44476669e+00]
 [-7.13435904e-01  2.59173306e+00 -1.67015426e+00 -2.07069672e+00
  -2.55357970e+00 -1.13167725e+00 -4.19289092e+00 -3.87131867e+00
  -2.84952827e+00 -1.53027151e+00]
 [ 6.99454374e-01  1.53582627e+00 -4.74895324e-02  3.43618370e+00
   4.24093076e+00  4.54572485e+00 -4.78490404e+00 -3.68864683e+00
  -4.97758208e+00 -3.52194965e+00]
 [-9.92657158e-01  2.00171876e+00  2.10078948e+00  4.81946315e+00
   4.15328898e+00  2.62224069e+00  3.05332476e+00  5.04135574e+00
   4.79450340e+00 -4.80564996e+00]
 [-9.94037001e-01  4.28095001e-02  2.09898054e+00  2.89355415e+00
   4.25039222e+00 -4.06073820e+00 -2.30291736e+00 -4.65590878e+00
  -2.31878381e+00 -1.68855052e+00]
 [-3.75204294e-01  1.50136007e+00  2.41485237e+00  3.38019751e+00
   3.23948956e+00  2.48403711e+00 -3.26888125e+00 -4.04966991e+00
  -3.97150302e+00 -1.68665097e+00]
 [-6.66285728e-01 -4.68317159e-01  2.93187725e+00 -7.17742546e-01
   1.17878650e+00  4.06462796e+00  5.06399558e+00  4.43765363e+00
  -4.85652133e+00 -1.04978645e+00]
 [-7.73694933e-01  1.66855531e+00  1.24656646e+00  7.75289579e-01
   4.98046098e+00  4.01623642e-01  2.48138014e+00 -3.81808876e+00
  -4.32452278e+00 -3.51736673e+00]
 [ 5.72412742e-01  1.16323060e+00  2.19015957e+00  3.78031260e+00
   4.87903936e+00  5.02028982e+00  3.77052422e+00 -2.34425111e+00
  -3.44033290e+00 -2.45882841e+00]
 [ 5.41972958e-01 -4.09217828e-03  2.18219824e+00 -2.54777808e+00
  -2.79572284e+00 -1.92956117e+00 -4.46132544e+00 -3.39368102e+00
  -2.95545777e+00 -1.17925928e+00]
 [-5.00078339e-01 -5.07184825e-01  2.28688275e+00  3.92222183e+00
   4.66833567e+00  2.51691123e+00  3.31132371e+00 -4.00906429e+00
  -3.00084593e+00 -2.50865375e+00]
 [ 2.35069948e-01  3.34239319e-01  2.77990959e+00  2.93068555e+00
   4.79692023e+00 -7.10287227e-01  4.04653618e+00 -5.05193967e+00
  -4.20464794e+00 -2.89168071e+00]
 [ 3.40696335e-02  1.77467784e+00  2.35387466e+00  1.81760635e+00
   1.63347394e+00 -4.09445547e+00 -3.04170401e+00 -4.67341624e+00
  -3.50499003e+00 -1.32572693e+00]
 [-4.98607412e-01  1.05187906e+00  1.79329921e+00  1.51938405e-02
   4.28307246e+00  4.41188111e+00 -2.22485851e+00 -2.12166766e+00
  -3.60884590e+00 -2.56232900e+00]]
McCormick Test Data:  [[ 0.43109351  2.84010295]
 [-1.22586554  1.16429815]
 [ 2.29320894 -2.07302072]
 [ 1.41216142 -2.36112549]
 [ 1.66692114  1.64615734]
 [ 2.74943903 -1.51667007]
 [ 1.46067186  0.76050157]
 [-1.41605276 -2.3093959 ]
 [ 2.68011812 -0.94868149]
 [-0.10744827 -1.53425764]
 [-1.19718117  1.32486851]
 [ 2.4699325  -1.60626482]
 [-1.48229047 -0.38788616]
 [ 1.164183    2.95800049]
 [ 3.63118806 -0.6837441 ]]
Dixon-Price Test Data:  [[-6.34028053 -5.9950218  -4.46352608 -2.22567653]
 [ 8.38760746 -5.56414937  6.11408453 -1.36382744]
 [-1.9639362   4.81525028  5.95992281 -9.67897179]
 [-6.89302765 -5.96317771 -9.57349711  7.76494528]
 [-8.23654725 -7.41956524 -5.94023468  8.04526261]
 [ 0.23365893 -5.87995539 -4.27469959 -3.81977523]
 [ 8.84998131  2.52253846 -4.61190059 -9.14163462]
 [ 1.08504763  2.12983531  2.14088832 -7.44205281]
 [ 8.37830339 -6.4038505  -5.31718418 -8.49853015]
 [-2.0749087   5.36964038 -3.70461808  6.62004665]
 [ 9.08991221 -4.48109618  1.12840386 -9.44061036]
 [-8.56612978  9.84369297  2.55171106  4.95056684]
 [ 0.41582087  5.96894    -3.37695909 -9.88145948]
 [ 0.74449726  1.37580473 -5.88047343 -4.54830302]
 [-8.53941011 -1.52997507 -2.74165682  7.78638792]]
Easom Test Data:  [[-4.18479627  5.57957106]
 [ 5.49070167 -1.40532341]
 [ 0.8740492   6.26710152]
 [ 3.26056803 -3.8487686 ]
 [-0.6555865   6.22496939]
 [ 0.92434982 -2.90783325]
 [ 3.46770817  3.35471267]
 [-5.56800021 -2.04506186]
 [-5.82926969 -4.75523721]
 [ 5.82254869 -1.80073482]
 [ 3.42371012 -3.72962696]
 [ 1.77398352 -4.02474149]
 [ 0.11739584  3.47748612]
 [ 1.45533291  2.8255561 ]
 [ 4.41729995 -1.08112248]]
Rastrigin Test Data:  [[-0.74043569  3.82734368  3.53072089  4.39947369 -1.11435004]
 [-0.84765357  3.37698545  4.14107766 -3.55346453 -1.11923651]
 [-0.27493895  0.14197663  2.9974006  -3.56588569 -2.08143437]
 [ 0.63862669  1.63077941 -0.6795415  -4.72449731 -1.34892503]
 [ 2.8553418   2.27631126  4.77185713 -3.45724238 -2.28045156]
 [ 0.76575916  3.15685024  3.83411081 -1.73865749 -1.18413576]
 [ 0.87553033  3.33093311 -3.07744352 -2.42873296 -1.38357083]
 [-0.45285547  2.91897455  2.75532159  5.02171625 -3.43129171]
 [-0.24745374  3.66655268  4.28479817 -4.55906376 -1.16317184]
 [ 0.31377102  0.18762378 -4.96886187 -4.84263311 -3.02729488]
 [ 0.93195051 -0.08027306  4.03985243 -3.76610909 -1.805593  ]
 [ 1.37901139  3.9590094  -2.41161112 -2.38003182 -1.70038976]
 [ 0.73252445  3.8443382   4.8867729  -3.333061   -2.54930341]
 [ 3.32033646 -1.58144857 -5.08022946 -3.1327846  -1.53064438]
 [ 0.97848023  3.03569021 -3.19841601 -3.22958704 -1.1536173 ]]

# Comparación: Función Esfera (10 variables)

In [169]:

# Descenso del Gradiente con condiciones fuertes de Wolfe

resultados_sphere_MDG_Wolfe = {}
resultados_sphere_Newton = {}
resultados_sphere_MDG_DM = {}

n_iter = 20
for i, test in enumerate(test_data_sphere):

    x_opt_1, trayectoria_1 = MDG_Wolfe(
        f        = sphere.f,
        Df       = sphere.Df,
        x0       = test,
        c1       = 1e-4,    # qué tan estricto es el descenso (Armijo)
        c2       = 0.9,     # qué tan estricta es la curvatura
        alph_max = 1.0,     # paso máximo que puede probar la búsqueda
        max_iter = n_iter
    )

    resultados_sphere_MDG_Wolfe[i] = {
        "x_optimo": x_opt_1,
        "llego_optimo": np.linalg.norm(x_opt_1 - np.array(sphere.global_min)) < sphere.tol,
        "dist": np.linalg.norm(x_opt_1 - np.array(sphere.global_min)),
        "trayectoria": trayectoria_1,
        "n_iter": n_iter,
        "f_invok": sphere.f_count_invok,
        "Df_invok": sphere.Df_count_invok,
        "H_invok": sphere.H_count_invok
    }

    sphere.f_count_invok = 0
    sphere.Df_count_invok = 0
    sphere.H_count_invok = 0

    x_opt_2, trayectoria_2 = NewtonMethod(
        G=sphere.Df,
        H=sphere.H,
        x0=test,
        max_iter=n_iter
    )

    resultados_sphere_Newton[i] = {
        "x_optimo": x_opt_2,
        "llego_optimo": np.linalg.norm(x_opt_2 - np.array(sphere.global_min)) < sphere.tol,
        "dist": np.linalg.norm(x_opt_2 - np.array(sphere.global_min)),
        "trayectoria": trayectoria_2,
        "n_iter": n_iter,
        "f_invok": sphere.f_count_invok,
        "Df_invok": sphere.Df_count_invok,
        "H_invok": sphere.H_count_invok
    }

    sphere.f_count_invok = 0
    sphere.Df_count_invok = 0
    sphere.H_count_invok = 0

    x_opt_3, trayectoria_3 = MDG_DM(
        f=sphere.f,
        Df=sphere.Df,
        x0=test,
        max_iter=n_iter
    )

    resultados_sphere_MDG_DM[i] = {
        "x_optimo": x_opt_3,
        "llego_optimo": np.linalg.norm(x_opt_3 - np.array(sphere.global_min)) < sphere.tol,
        "dist": np.linalg.norm(x_opt_3 - np.array(sphere.global_min)),
        "trayectoria": trayectoria_3,
        "n_iter": n_iter,
        "f_invok": sphere.f_count_invok,
        "Df_invok": sphere.Df_count_invok,
        "H_invok": sphere.H_count_invok
    }

    sphere.f_count_invok = 0
    sphere.Df_count_invok = 0
    sphere.H_count_invok = 0

tabla_sphere = crear_tabla_comparativa(
    resultados_por_metodo={
        "MDG_Wolfe": resultados_sphere_MDG_Wolfe,
        "Newton":    resultados_sphere_Newton,
        "MDG_DM":    resultados_sphere_MDG_DM,
    },
    nombre_funcion="Sphere"
)

resumen_sphere = resumen_tabla(tabla_sphere)

display(tabla_sphere)
display(resumen_sphere)

📊 Tabla comparativa — Sphere
📋 Resumen por método

,Punto,Método,x_optimo,llego_optimo,dist,n_iter,f_invok,Df_invok,H_invok
0,1,MDG_DM,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0....",True,9.616580e-80,20,320,340,0
1,1,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
2,1,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
3,2,MDG_DM,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0....",True,7.667599e-80,20,320,340,0
4,2,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
5,2,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
6,3,MDG_DM,"[-0.0, 0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0...",True,8.070546e-80,20,320,340,0
7,3,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
8,3,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
9,4,MDG_DM,"[0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0...",True,1.126892e-79,20,320,340,0
10,4,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
11,4,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
12,5,MDG_DM,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...",True,1.172938e-79,20,320,340,0
13,5,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
14,5,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
15,6,MDG_DM,"[-0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -...",True,9.139618e-80,20,320,340,0
16,6,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
17,6,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
18,7,MDG_DM,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0...",True,9.056483e-80,20,320,340,0
19,7,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
20,7,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
21,8,MDG_DM,"[-0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0...",True,9.884823e-80,20,320,340,0
22,8,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
23,8,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
24,9,MDG_DM,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0....",True,9.072618e-80,20,320,340,0
25,9,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
26,9,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
27,10,MDG_DM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0...",True,1.036199e-79,20,320,340,0
28,10,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
29,10,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
30,11,MDG_DM,"[0.0, -0.0, 0.0, -0.0, -0.0, -0.0, -0.0, -0.0,...",True,8.039407e-80,20,320,340,0
31,11,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
32,11,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
33,12,MDG_DM,"[-0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0...",True,9.570008e-80,20,320,340,0
34,12,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
35,12,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
36,13,MDG_DM,"[0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0.0, -0....",True,1.038923e-79,20,320,340,0
37,13,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
38,13,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
39,14,MDG_DM,"[0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0...",True,8.750037e-80,20,320,340,0
40,14,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
41,14,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2
42,15,MDG_DM,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0...",True,8.451117e-80,20,320,340,0
43,15,MDG_Wolfe,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,42,60,0
44,15,Newton,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",True,0.000000e+00,20,0,2,2

,Método,Llegó al óptimo,Mejor dist,Mejor x_optimo,Avg f_invok,Avg Df_invok,Avg H_invok
0,MDG_DM,15/15,0.0,"[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0....",320.0,340.0,0.0
1,MDG_Wolfe,15/15,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",42.0,60.0,0.0
2,Newton,15/15,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.0,2.0,2.0

# Comparación: Función McCormick (2 variables)

In [170]:
# Descenso del Gradiente con condiciones fuertes de Wolfe

resultados_mcCormick_MDG_Wolfe = {}
resultados_mcCormick_Newton = {}
resultados_mcCormick_MDG_DM = {}

n_iter = 20
for i, test in enumerate(test_data_mcCormick):

    x_opt_1, trayectoria_1 = MDG_Wolfe(
        f        = mcCormick.f,
        Df       = mcCormick.Df,
        x0       = test,
        c1       = 1e-4,    # qué tan estricto es el descenso (Armijo)
        c2       = 0.9,     # qué tan estricta es la curvatura
        alph_max = 1.0,     # paso máximo que puede probar la búsqueda
        max_iter = n_iter
    )

    resultados_mcCormick_MDG_Wolfe[i] = {
        "x_optimo": x_opt_1,
        "llego_optimo": np.linalg.norm(x_opt_1 - np.array(mcCormick.global_min)) < mcCormick.tol,
        "dist": np.linalg.norm(x_opt_1 - np.array(mcCormick.global_min)),
        "trayectoria": trayectoria_1,
        "n_iter": n_iter,
        "f_invok": mcCormick.f_count_invok,
        "Df_invok": mcCormick.Df_count_invok,
        "H_invok": mcCormick.H_count_invok
    }

    mcCormick.f_count_invok = 0
    mcCormick.Df_count_invok = 0
    mcCormick.H_count_invok = 0

    x_opt_2, trayectoria_2 = NewtonMethod(
        G=mcCormick.Df,
        H=mcCormick.H,
        x0=test,
        max_iter=n_iter
    )

    resultados_mcCormick_Newton[i] = {
        "x_optimo": x_opt_2,
        "llego_optimo": np.linalg.norm(x_opt_2 - np.array(mcCormick.global_min)) < mcCormick.tol,
        "dist": np.linalg.norm(x_opt_2 - np.array(mcCormick.global_min)),
        "trayectoria": trayectoria_2,
        "n_iter": n_iter,
        "f_invok": mcCormick.f_count_invok,
        "Df_invok": mcCormick.Df_count_invok,
        "H_invok": mcCormick.H_count_invok
    }

    mcCormick.f_count_invok = 0
    mcCormick.Df_count_invok = 0
    mcCormick.H_count_invok = 0

    x_opt_3, trayectoria_3 = MDG_DM(
        f=mcCormick.f,
        Df=mcCormick.Df,
        x0=test,
        max_iter=n_iter
    )

    resultados_mcCormick_MDG_DM[i] = {
        "x_optimo": x_opt_3,
        "llego_optimo": np.linalg.norm(x_opt_3 - np.array(mcCormick.global_min)) < mcCormick.tol,
        "dist": np.linalg.norm(x_opt_3 - np.array(mcCormick.global_min)),
        "trayectoria": trayectoria_3,
        "n_iter": n_iter,
        "f_invok": mcCormick.f_count_invok,
        "Df_invok": mcCormick.Df_count_invok,
        "H_invok": mcCormick.H_count_invok
    }

    mcCormick.f_count_invok = 0
    mcCormick.Df_count_invok = 0
    mcCormick.H_count_invok = 0

tabla_mcCormick = crear_tabla_comparativa(
    resultados_por_metodo={
        "MDG_Wolfe": resultados_mcCormick_MDG_Wolfe,
        "Newton":    resultados_mcCormick_Newton,
        "MDG_DM":    resultados_mcCormick_MDG_DM,
    },
    nombre_funcion="McCormick"
)

resumen_mcCormick = resumen_tabla(tabla_mcCormick)


display(tabla_mcCormick)
display(resumen_mcCormick)

📊 Tabla comparativa — McCormick
📋 Resumen por método

,Punto,Método,x_optimo,llego_optimo,dist,n_iter,f_invok,Df_invok,H_invok
0,1,MDG_DM,"[5.7736, 4.7501]",False,8.922344,20,368,388,0
1,1,MDG_Wolfe,"[7.119, 4.403]",False,9.704442,20,1089,44,0
2,1,Newton,"[793.1754, 775.5844]",False,1110.823587,20,0,20,20
3,2,MDG_DM,"[2.6993, 1.6288]",False,4.541587,20,392,412,0
4,2,MDG_Wolfe,"[3.3824, 0.7726]",False,4.563280,20,1032,42,0
5,2,Newton,"[1285.3816, 1267.7717]",False,1806.871136,20,0,20,20
6,3,MDG_DM,"[11.8361, 10.9241]",False,17.574943,20,480,500,0
7,3,MDG_Wolfe,"[1.9726, -2.5499]",False,2.711944,20,1111,49,0
8,3,Newton,"[110.319, 85.9528]",False,141.235804,20,0,20,20
9,4,MDG_DM,"[3.6806, 1.4579]",False,5.187003,20,552,572,0
10,4,MDG_Wolfe,"[1.4122, -2.3611]",False,2.121685,20,1045,41,0
11,4,Newton,"[-590.446, -614.2193]",False,850.498515,20,0,20,20
12,5,MDG_DM,"[2.2813, 1.4055]",False,4.088833,20,368,388,0
13,5,MDG_Wolfe,"[2.8888, 0.8681]",False,4.199955,20,992,41,0
14,5,Newton,"[-189.7461, -209.7669]",False,281.339040,20,0,20,20
15,6,MDG_DM,"[4.4139, 1.063]",False,5.605820,20,536,556,0
16,6,MDG_Wolfe,"[2.7494, -1.5167]",False,3.296770,20,1041,40,0
17,6,Newton,"[151.2161, 126.95]",False,198.855832,20,0,20,20
18,7,MDG_DM,"[1.5164, 0.4551]",False,2.875307,20,368,388,0
19,7,MDG_Wolfe,"[1.5488, 0.3486]",False,2.826204,20,1087,41,0
20,7,Newton,"[-17.4595, -38.1596]",False,40.329830,20,0,20,20
21,8,MDG_DM,"[-1.4179, -2.2972]",False,1.149232,20,320,340,0
22,8,MDG_Wolfe,"[-1.4161, -2.3094]",False,1.155803,20,1069,47,0
23,8,Newton,"[-127.2635, -148.1568]",False,193.781859,20,0,20,20
24,9,MDG_DM,"[5.6482, 4.6962]",False,8.795606,20,440,460,0
25,9,MDG_Wolfe,"[2.6801, -0.9487]",False,3.282336,20,1040,40,0
26,9,Newton,"[-1012.4757, -1036.1045]",False,1447.172481,20,0,20,20
27,10,MDG_DM,"[-0.097, -1.4914]",False,0.453587,20,360,380,0
28,10,MDG_Wolfe,"[-0.1074, -1.5343]",False,0.439932,20,1044,41,0
29,10,Newton,"[2722.3817, 2700.9549]",False,3836.386193,20,0,20,20
30,11,MDG_DM,"[2.7879, 1.6467]",False,4.617814,20,408,428,0
31,11,MDG_Wolfe,"[3.8455, 1.3675]",False,5.271698,20,1055,45,0
32,11,Newton,"[-122.057, -139.5349]",False,183.862040,20,0,20,20
33,12,MDG_DM,"[7.8795, 6.9357]",False,11.956984,20,424,444,0
34,12,MDG_Wolfe,"[1.8582, -2.5461]",False,2.604582,20,1142,46,0
35,12,Newton,"[717.0087, 692.9325]",False,998.593265,20,0,20,20
36,13,MDG_DM,"[-0.1092, -1.49]",False,0.441689,20,416,436,0
37,13,MDG_Wolfe,"[0.1834, -1.7222]",False,0.751251,20,1041,42,0
38,13,Newton,"[284.1333, 265.2277]",False,390.143350,20,0,20,20
39,14,MDG_DM,"[5.6547, 4.6995]",False,8.802535,20,408,428,0
40,14,MDG_Wolfe,"[6.8083, 4.6022]",False,9.587417,20,1045,61,0
41,14,Newton,"[51.945, 33.7388]",False,63.249792,20,0,20,20
42,15,MDG_DM,"[6.8064, 4.6066]",False,9.588795,20,576,596,0
43,15,MDG_Wolfe,"[3.6312, -0.6837]",False,4.266659,20,1040,40,0
44,15,Newton,"[136.4454, 112.1305]",False,178.015650,20,0,20,20

,Método,Llegó al óptimo,Mejor dist,Mejor x_optimo,Avg f_invok,Avg Df_invok,Avg H_invok
0,MDG_DM,0/15,—,None,427.73,447.73,0.0
1,MDG_Wolfe,0/15,—,None,1058.20,44.00,0.0
2,Newton,0/15,—,None,0.00,20.00,20.0

# Comparación: Función de Dixon-Price (4 variables)

In [171]:

resultados_dixon_price_MDG_Wolfe = {}
resultados_dixon_price_Newton = {}
resultados_dixon_price_MDG_DM = {}

n_iter = 20
for i, test in enumerate(test_data_dixon_price):

    x_opt_1, trayectoria_1 = MDG_Wolfe(
        f        = dixon_price.f,
        Df       = dixon_price.Df,
        x0       = test,
        c1       = 1e-4,    # qué tan estricto es el descenso (Armijo)
        c2       = 0.9,     # qué tan estricta es la curvatura
        alph_max = 1.0,     # paso máximo que puede probar la búsqueda
        max_iter = n_iter
    )

    resultados_dixon_price_MDG_Wolfe[i] = {
        "x_optimo": x_opt_1,
        "llego_optimo": np.linalg.norm(x_opt_1 - np.array(dixon_price.global_min)) < dixon_price.tol,
        "dist": np.linalg.norm(x_opt_1 - np.array(dixon_price.global_min)),
        "trayectoria": trayectoria_1,
        "n_iter": n_iter,
        "f_invok": dixon_price.f_count_invok,
        "Df_invok": dixon_price.Df_count_invok,
        "H_invok": dixon_price.H_count_invok
    }

    dixon_price.f_count_invok = 0
    dixon_price.Df_count_invok = 0
    dixon_price.H_count_invok = 0

    x_opt_2, trayectoria_2 = NewtonMethod(
        G=dixon_price.Df,
        H=dixon_price.H,
        x0=test,
        max_iter=n_iter
    )

    resultados_dixon_price_Newton[i] = {
        "x_optimo": x_opt_2,
        "llego_optimo": np.linalg.norm(x_opt_2 - np.array(dixon_price.global_min)) < dixon_price.tol,
        "dist": np.linalg.norm(x_opt_2 - np.array(dixon_price.global_min)),
        "trayectoria": trayectoria_2,
        "n_iter": n_iter,
        "f_invok": dixon_price.f_count_invok,
        "Df_invok": dixon_price.Df_count_invok,
        "H_invok": dixon_price.H_count_invok
    }

    dixon_price.f_count_invok = 0
    dixon_price.Df_count_invok = 0
    dixon_price.H_count_invok = 0

    x_opt_3, trayectoria_3 = MDG_DM(
        f=dixon_price.f,
        Df=dixon_price.Df,
        x0=test,
        max_iter=n_iter
    )

    resultados_dixon_price_MDG_DM[i] = {
        "x_optimo": x_opt_3,
        "llego_optimo": np.linalg.norm(x_opt_3 - np.array(dixon_price.global_min)) < dixon_price.tol,
        "dist": np.linalg.norm(x_opt_3 - np.array(dixon_price.global_min)),
        "trayectoria": trayectoria_3,
        "n_iter": n_iter,
        "f_invok": dixon_price.f_count_invok,
        "Df_invok": dixon_price.Df_count_invok,
        "H_invok": dixon_price.H_count_invok
    }

    dixon_price.f_count_invok = 0
    dixon_price.Df_count_invok = 0
    dixon_price.H_count_invok = 0

tabla_dixon_price = crear_tabla_comparativa(
    resultados_por_metodo={
        "MDG_Wolfe": resultados_dixon_price_MDG_Wolfe,
        "Newton":    resultados_dixon_price_Newton,
        "MDG_DM":    resultados_dixon_price_MDG_DM,
    },
    nombre_funcion="Dixon-Price"
)

resumen_dixon_price = resumen_tabla(tabla_dixon_price)

display(tabla_dixon_price)
display(resumen_dixon_price)

📊 Tabla comparativa — Dixon-Price
📋 Resumen por método

,Punto,Método,x_optimo,llego_optimo,dist,n_iter,f_invok,Df_invok,H_invok
0,1,MDG_DM,"[-6.3402, -5.9945, -4.4631, -2.2255]",False,11.491237,20,320,340,0
1,1,MDG_Wolfe,"[0.3331, 0.0009, 0.001, -0.0222]",False,1.271963,20,123,60,0
2,1,Newton,"[0.333, 0.0044, -0.0, -0.0]",False,1.260771,20,0,20,20
3,2,MDG_DM,"[8.3876, -5.5641, 6.1139, -1.3638]",False,11.314256,20,320,340,0
4,2,MDG_Wolfe,"[1.8999, 0.9608, 0.7424, -0.5335]",False,1.435153,20,168,61,0
5,2,Newton,"[0.3324, -0.0532, -0.0935, 0.2239]",False,1.265121,20,0,20,20
6,3,MDG_DM,"[-1.9639, 4.8153, 5.9599, -9.679]",False,12.608850,20,320,340,0
7,3,MDG_Wolfe,"[0.477, 0.3754, 0.4248, -0.4059]",False,1.147689,20,154,63,0
8,3,Newton,"[1.0116, 0.7132, 0.5972, -0.5464]",False,1.091783,20,0,20,20
9,4,MDG_DM,"[-6.893, -5.9632, -9.5735, 7.7649]",False,16.195870,20,320,340,0
10,4,MDG_Wolfe,"[0.3396, 0.0268, -0.0, -0.0006]",False,1.245172,20,165,62,0
11,4,Newton,"[0.3331, -0.0065, -0.0002, 0.0]",False,1.266869,20,0,20,20
12,5,MDG_DM,"[-8.2365, -7.4196, -5.9402, 8.0453]",False,15.821207,20,320,340,0
13,5,MDG_Wolfe,"[0.3331, 0.0004, 0.0002, -0.0011]",False,1.263339,20,129,62,0
14,5,Newton,"[0.3185, -0.0302, -0.0, 0.0001]",False,1.287979,20,0,20,20
15,6,MDG_DM,"[0.2337, -5.8797, -4.2745, -3.8195]",False,9.313010,20,320,340,0
16,6,MDG_Wolfe,"[0.9143, 0.672, 0.5768, 0.5391]",False,0.094538,20,159,62,0
17,6,Newton,"[0.3333, -0.0008, -0.0, -0.0]",False,1.263501,20,0,20,20
18,7,MDG_DM,"[8.85, 2.5225, -4.6119, -9.1416]",False,13.633099,20,320,340,0
19,7,MDG_Wolfe,"[4.9037, 1.6018, -0.7664, 0.0]",False,4.264894,20,187,60,0
20,7,Newton,"[0.3331, 0.0001, 0.0077, -0.0]",False,1.259482,20,0,20,20
21,8,MDG_DM,"[1.085, 2.1298, 2.1409, -7.442]",False,8.259493,20,320,340,0
22,8,MDG_Wolfe,"[0.3426, 0.0297, 0.0, 0.0]",False,1.241705,20,142,60,0
23,8,Newton,"[1.0004, 0.7073, 0.5947, -0.5453]",False,1.090546,20,0,20,20
24,9,MDG_DM,"[8.3783, -6.4038, -5.3172, -8.4985]",False,14.891077,20,320,340,0
25,9,MDG_Wolfe,"[5.7641, 1.5601, -0.8415, 0.0]",False,5.077804,20,192,60,0
26,9,Newton,"[0.3326, 0.0062, -0.0, -0.0002]",False,1.260067,20,0,20,20
27,10,MDG_DM,"[-2.0749, 5.3696, -3.7046, 6.62]",False,9.304858,20,320,340,0
28,10,MDG_Wolfe,"[0.3334, 0.0003, 0.0004, -0.0143]",False,1.268951,20,126,61,0
29,10,Newton,"[0.3333, -0.0001, 0.0006, 0.0]",False,1.262860,20,0,20,20
30,11,MDG_DM,"[9.0899, -4.4811, 1.1284, -9.4406]",False,13.869624,20,320,340,0
31,11,MDG_Wolfe,"[2.484, 1.1703, -0.4058, -0.0]",False,1.927402,20,177,60,0
32,11,Newton,"[0.3333, -0.0003, 0.0008, -0.0224]",False,1.272639,20,0,20,20
33,12,MDG_DM,"[-8.5661, 9.8436, 2.5517, 4.9505]",False,14.079139,20,320,340,0
34,12,MDG_Wolfe,"[0.8005, 0.6172, 0.5581, -0.5159]",False,1.084106,20,159,62,0
35,12,Newton,"[1.1266, 0.7725, 0.6221, 0.5578]",False,0.145615,20,0,20,20
36,13,MDG_DM,"[0.4158, 5.9689, -3.377, -9.8815]",False,12.349807,20,320,340,0
37,13,MDG_Wolfe,"[0.7953, 0.6193, 0.5446, 0.5345]",False,0.228568,20,178,62,0
38,13,Newton,"[22.276, -4.1627, 4.3787, -0.0]",False,22.158543,20,0,20,20
39,14,MDG_DM,"[0.7445, 1.3758, -5.8804, -4.5482]",False,8.269275,20,320,340,0
40,14,MDG_Wolfe,"[0.3333, -0.0017, 0.0005, -0.0221]",False,1.273463,20,123,60,0
41,14,Newton,"[0.3328, 0.009, 0.0056, -0.0]",False,1.255665,20,0,20,20
42,15,MDG_DM,"[-8.5394, -1.53, -2.7417, 7.7864]",False,12.632077,20,320,340,0
43,15,MDG_Wolfe,"[0.3417, 0.026, 0.0, 0.0035]",False,1.242714,20,154,61,0
44,15,Newton,"[0.3333, -0.0005, 0.0, 0.0051]",False,1.261096,20,0,20,20

,Método,Llegó al óptimo,Mejor dist,Mejor x_optimo,Avg f_invok,Avg Df_invok,Avg H_invok
0,MDG_DM,0/15,—,None,320.00,340.00,0.0
1,MDG_Wolfe,0/15,—,None,155.73,61.07,0.0
2,Newton,0/15,—,None,0.00,20.00,20.0

# Comparación: Función de Easom (2 variables)

In [172]:

resultados_easom_MDG_Wolfe = {}
resultados_easom_Newton = {}
resultados_easom_MDG_DM = {}

n_iter = 20
for i, test in enumerate(test_data_easom):

    x_opt_1, trayectoria_1 = MDG_Wolfe(
        f        = easom.f,
        Df       = easom.Df,
        x0       = test,
        c1       = 1e-4,    # qué tan estricto es el descenso (Armijo)
        c2       = 0.9,     # qué tan estricta es la curvatura
        alph_max = 1.0,     # paso máximo que puede probar la búsqueda
        max_iter = n_iter
    )

    resultados_easom_MDG_Wolfe[i] = {
        "x_optimo": x_opt_1,
        "llego_optimo": np.linalg.norm(x_opt_1 - np.array(easom.global_min)) < easom.tol,
        "dist": np.linalg.norm(x_opt_1 - np.array(easom.global_min)),
        "trayectoria": trayectoria_1,
        "n_iter": n_iter,
        "f_invok": easom.f_count_invok,
        "Df_invok": easom.Df_count_invok,
        "H_invok": easom.H_count_invok
    }

    easom.f_count_invok = 0
    easom.Df_count_invok = 0
    easom.H_count_invok = 0

    x_opt_2, trayectoria_2 = NewtonMethod(
        G=easom.Df,
        H=easom.H,
        x0=test,
        max_iter=n_iter
    )

    resultados_easom_Newton[i] = {
        "x_optimo": x_opt_2,
        "llego_optimo": np.linalg.norm(x_opt_2 - np.array(easom.global_min)) < easom.tol,
        "dist": np.linalg.norm(x_opt_2 - np.array(easom.global_min)),
        "trayectoria": trayectoria_2,
        "n_iter": n_iter,
        "f_invok": easom.f_count_invok,
        "Df_invok": easom.Df_count_invok,
        "H_invok": easom.H_count_invok
    }

    easom.f_count_invok = 0
    easom.Df_count_invok = 0
    easom.H_count_invok = 0

    x_opt_3, trayectoria_3 = MDG_DM(
        f=easom.f,
        Df=easom.Df,
        x0=test,
        max_iter=n_iter
    )

    resultados_easom_MDG_DM[i] = {
        "x_optimo": x_opt_3,
        "llego_optimo": np.linalg.norm(x_opt_3 - np.array(easom.global_min)) < easom.tol,
        "dist": np.linalg.norm(x_opt_3 - np.array(easom.global_min)),
        "trayectoria": trayectoria_3,
        "n_iter": n_iter,
        "f_invok": easom.f_count_invok,
        "Df_invok": easom.Df_count_invok,
        "H_invok": easom.H_count_invok
    }

    easom.f_count_invok = 0
    easom.Df_count_invok = 0
    easom.H_count_invok = 0

tabla_easom = crear_tabla_comparativa(
    resultados_por_metodo={
        "MDG_Wolfe": resultados_easom_MDG_Wolfe,
        "Newton":    resultados_easom_Newton,
        "MDG_DM":    resultados_easom_MDG_DM,
    },
    nombre_funcion="Easom"
)

resumen_easom = resumen_tabla(tabla_easom)

display(tabla_easom)
display(resumen_easom)

📊 Tabla comparativa — Easom
📋 Resumen por método

/Users/mardnstuff/Documents/dev/MARDGithub/mard-numerical-methods/numerical_methods/max_decrease.py:20: RuntimeWarning: invalid value encountered in scalar divide
  xk1 = (df(xk1)*xk - df(xk)*xk1) / (df(xk1) - df(xk))
/Users/mardnstuff/Documents/dev/MARDGithub/mard-numerical-methods/numerical_methods/max_decrease.py:20: RuntimeWarning: divide by zero encountered in scalar divide
  xk1 = (df(xk1)*xk - df(xk)*xk1) / (df(xk1) - df(xk))
/Users/mardnstuff/Documents/dev/MARDGithub/mard-numerical-methods/functions/easom_foo.py:27: RuntimeWarning: invalid value encountered in cos
  return -1*cos(x[0])*cos(x[1])*exp(-1*(x[0] - pi)**2 - (x[1] - pi)**2)

,Punto,Método,x_optimo,llego_optimo,dist,n_iter,f_invok,Df_invok,H_invok
0,1,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
1,1,MDG_Wolfe,"[-4.1848, 5.5796]",False,7.721380e+00,20,2080,60,0
2,1,Newton,"[2.7839, -10.0486]",False,1.319508e+01,20,0,20,20
3,2,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
4,2,MDG_Wolfe,"[5.4907, -1.4053]",False,5.117886e+00,20,2080,60,0
5,2,Newton,"[2.7812, -0.8777]",False,4.035395e+00,20,0,20,20
6,3,MDG_DM,"[nan, nan]",False,NaN,20,3048,3068,0
7,3,MDG_Wolfe,"[0.8741, 6.2671]",False,3.861389e+00,20,2080,60,0
8,3,Newton,"[-17.5915, 9.674]",False,2.173782e+01,20,0,20,20
9,4,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
10,4,MDG_Wolfe,"[3.2606, -3.8488]",False,6.991374e+00,20,2080,60,0
11,4,Newton,"[3.5403, -4.3385]",False,7.490691e+00,20,0,20,20
12,5,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
13,5,MDG_Wolfe,"[-0.6556, 6.225]",False,4.891399e+00,20,2080,60,0
14,5,Newton,"[0.093, 3.3097]",False,3.053266e+00,20,0,20,20
15,6,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
16,6,MDG_Wolfe,"[0.9243, -2.9078]",False,6.442959e+00,20,2080,60,0
17,6,Newton,"[2.8191, -2.7919]",False,5.942283e+00,20,0,20,20
18,7,MDG_DM,"[nan, nan]",False,NaN,20,2928,2948,0
19,7,MDG_Wolfe,"[3.1416, 3.1416]",True,1.471734e-07,20,80,60,0
20,7,Newton,"[3.1416, 3.1416]",True,2.663097e-05,20,0,13,13
21,8,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
22,8,MDG_Wolfe,"[-5.568, -2.0451]",False,1.013698e+01,20,2080,60,0
23,8,Newton,"[-7.5743, -5.3268]",False,1.365810e+01,20,0,20,20
24,9,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
25,9,MDG_Wolfe,"[-5.8293, -4.7552]",False,1.195141e+01,20,2080,60,0
26,9,Newton,"[-3.2079, -2.3007]",False,8.362666e+00,20,0,20,20
27,10,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
28,10,MDG_Wolfe,"[5.8225, -1.8007]",False,5.622644e+00,20,2080,60,0
29,10,Newton,"[6.4249, -2.4312]",False,6.468084e+00,20,0,20,20
30,11,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
31,11,MDG_Wolfe,"[3.4237, -3.7296]",False,6.877009e+00,20,2080,60,0
32,11,Newton,"[3.5027, -4.1744]",False,7.324902e+00,20,0,20,20
33,12,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
34,12,MDG_Wolfe,"[1.774, -4.0247]",False,7.295663e+00,20,2080,60,0
35,12,Newton,"[3.4929, -4.2815]",False,7.431444e+00,20,0,20,20
36,13,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
37,13,MDG_Wolfe,"[0.1071, 3.4793]",False,3.053235e+00,20,2080,60,0
38,13,Newton,"[-0.7939, 3.507]",False,3.952422e+00,20,0,20,20
39,14,MDG_DM,"[1.305, 3.1416]",False,1.836597e+00,20,568,588,0
40,14,MDG_Wolfe,"[3.1416, 3.1416]",True,3.304963e-05,20,778,60,0
41,14,Newton,"[3.1865, 3.877]",False,7.368051e-01,20,0,20,20
42,15,MDG_DM,"[nan, nan]",False,NaN,20,3200,3220,0
43,15,MDG_Wolfe,"[4.4173, -1.0811]",False,4.411208e+00,20,2080,60,0
44,15,Newton,"[3.4376, -2.3753]",False,5.524863e+00,20,0,20,20

,Método,Llegó al óptimo,Mejor dist,Mejor x_optimo,Avg f_invok,Avg Df_invok,Avg H_invok
0,MDG_DM,0/15,—,None,2996.27,3016.27,0.00
1,MDG_Wolfe,2/15,0.0,"[3.1416, 3.1416]",1859.87,60.00,0.00
2,Newton,1/15,0.000027,"[3.1416, 3.1416]",0.00,19.53,19.53

# Comparación: Función de Rastrigin (5 variables)

In [173]:

resultados_rastrigin_MDG_Wolfe = {}
resultados_rastrigin_Newton = {}
resultados_rastrigin_MDG_DM = {}

n_iter = 20
for i, test in enumerate(test_data_rastrigin):

    x_opt_1, trayectoria_1 = MDG_Wolfe(
        f        = rastrigin.f,
        Df       = rastrigin.Df,
        x0       = test,
        c1       = 1e-4,    # qué tan estricto es el descenso (Armijo)
        c2       = 0.9,     # qué tan estricta es la curvatura
        alph_max = 1.0,     # paso máximo que puede probar la búsqueda
        max_iter = n_iter
    )

    resultados_rastrigin_MDG_Wolfe[i] = {
        "x_optimo": x_opt_1,
        "llego_optimo": np.linalg.norm(x_opt_1 - np.array(rastrigin.global_min)) < rastrigin.tol,
        "dist": np.linalg.norm(x_opt_1 - np.array(rastrigin.global_min)),
        "trayectoria": trayectoria_1,
        "n_iter": n_iter,
        "f_invok": rastrigin.f_count_invok,
        "Df_invok": rastrigin.Df_count_invok,
        "H_invok": rastrigin.H_count_invok
    }

    rastrigin.f_count_invok = 0
    rastrigin.Df_count_invok = 0
    rastrigin.H_count_invok = 0

    x_opt_2, trayectoria_2 = NewtonMethod(
        G=rastrigin.Df,
        H=rastrigin.H,
        x0=test,
        max_iter=n_iter
    )

    resultados_rastrigin_Newton[i] = {
        "x_optimo": x_opt_2,
        "llego_optimo": np.linalg.norm(x_opt_2 - np.array(rastrigin.global_min)) < rastrigin.tol,
        "dist": np.linalg.norm(x_opt_2 - np.array(rastrigin.global_min)),
        "trayectoria": trayectoria_2,
        "n_iter": n_iter,
        "f_invok": rastrigin.f_count_invok,
        "Df_invok": rastrigin.Df_count_invok,
        "H_invok": rastrigin.H_count_invok
    }

    rastrigin.f_count_invok = 0
    rastrigin.Df_count_invok = 0
    rastrigin.H_count_invok = 0

    x_opt_3, trayectoria_3 = MDG_DM(
        f=rastrigin.f,
        Df=rastrigin.Df,
        x0=test,
        max_iter=n_iter
    )

    resultados_rastrigin_MDG_DM[i] = {
        "x_optimo": x_opt_3,
        "llego_optimo": np.linalg.norm(x_opt_3 - np.array(rastrigin.global_min)) < rastrigin.tol,
        "dist": np.linalg.norm(x_opt_3 - np.array(rastrigin.global_min)),
        "trayectoria": trayectoria_3,
        "n_iter": n_iter,
        "f_invok": rastrigin.f_count_invok,
        "Df_invok": rastrigin.Df_count_invok,
        "H_invok": rastrigin.H_count_invok
    }

    rastrigin.f_count_invok = 0
    rastrigin.Df_count_invok = 0
    rastrigin.H_count_invok = 0

tabla_rastrigin = crear_tabla_comparativa(
    resultados_por_metodo={
        "MDG_Wolfe": resultados_rastrigin_MDG_Wolfe,
        "Newton":    resultados_rastrigin_Newton,
        "MDG_DM":    resultados_rastrigin_MDG_DM,
    },
    nombre_funcion="Rastrigin"
)

resumen_rastrigin = resumen_tabla(tabla_rastrigin)

display(tabla_rastrigin)  # display() renderiza mejor que print en notebooks
display(resumen_rastrigin)

📊 Tabla comparativa — Rastrigin
📋 Resumen por método

,Punto,Método,x_optimo,llego_optimo,dist,n_iter,f_invok,Df_invok,H_invok
0,1,MDG_DM,"[-15.4357, -6.9106, -16.5068, -4.6669, 12.7444]",False,27.252352,20,2200,2220,0
1,1,MDG_Wolfe,"[0.9947, -0.0002, 0.9948, -0.0001, -2.985]",False,3.299877,20,428,61,0
2,1,Newton,"[1.9899, 3.9798, 3.5179, 4.523, -0.995]",False,7.322648,20,0,4,4
3,2,MDG_DM,"[17.4236, -2.0794, -6.6338, -21.8268, -2.2918]",False,28.871710,20,2320,2340,0
4,2,MDG_Wolfe,"[-1.9872, 1.989, 1.9914, -3.9797, 0.0025]",False,5.263885,20,810,54,0
5,2,Newton,"[-0.995, 3.5179, 3.9798, -3.5179, -0.995]",False,6.524510,20,0,4,4
6,3,MDG_DM,"[0.6441, -8.4557, 6.0458, -7.424, 10.6428]",False,16.638888,20,2216,2236,0
7,3,MDG_Wolfe,"[-0.0006, -0.0009, 2.9847, -3.9801, -1.9891]",False,5.357771,20,740,50,0
8,3,Newton,"[-1.5076, 0.0, 2.9849, -3.5179, -1.9899]",False,5.245706,20,0,6,6
9,4,MDG_DM,"[2.9894, 13.7586, 2.9888, 7.5296, -4.8804]",False,16.961191,20,2280,2300,0
10,4,MDG_Wolfe,"[0.994, 1.9924, -0.9862, -4.9652, -1.0009]",False,5.620034,20,850,51,0
11,4,Newton,"[0.5025, 1.5076, -0.5025, -3.9798, -1.5076]",False,4.570530,20,0,5,5
12,5,MDG_DM,"[-12.7907, 4.6618, -3.5498, -20.8508, 14.1363]",False,28.853541,20,2088,2108,0
13,5,MDG_Wolfe,"[1.991, 0.9992, 4.9581, -0.0, -0.988]",False,5.524589,20,840,49,0
14,5,Newton,"[2.9849, 3.5179, 4.9747, -3.5179, -3.9798]",False,8.616627,20,0,7,7
15,6,MDG_DM,"[-10.6227, 16.6327, -10.9092, -3.528, -13.938]",False,26.743460,20,2264,2284,0
16,6,MDG_Wolfe,"[0.9956, 2.9813, 3.9821, -1.9886, -0.9921]",False,5.538546,20,923,56,0
17,6,Newton,"[18.8973, 2.9849, 3.9798, 0.5025, -1.9899]",False,19.648603,20,0,9,9
18,7,MDG_DM,"[-7.2052, -9.2369, 10.9191, 2.7111, -5.8499]",False,17.263666,20,2144,2164,0
19,7,MDG_Wolfe,"[2.9814, -0.0086, -2.9768, -2.9824, 0.0045]",False,5.161872,20,717,52,0
20,7,Newton,"[0.995, 3.5179, -2.9849, -2.5127, -1.5076]",False,5.555313,20,0,5,5
21,8,MDG_DM,"[-5.8989, 4.6623, 11.3471, -10.6951, 0.0346]",False,17.311168,20,2272,2292,0
22,8,MDG_Wolfe,"[1.9921, 1.9889, 0.996, 5.9634, -0.9889]",False,6.742144,20,837,46,0
23,8,Newton,"[-0.5025, 2.9849, 6.5333, 4.9747, -3.5179]",False,9.432357,20,0,3,3
24,9,MDG_DM,"[-0.6375, -7.0064, 5.7263, -13.8142, -3.1268]",False,16.819538,20,2560,2580,0
25,9,MDG_Wolfe,"[3.9864, 1.9921, 0.9886, -5.9553, 0.0013]",False,7.503497,20,813,58,0
26,9,Newton,"[7.5386, 3.5179, 4.9747, -4.523, -0.995]",False,10.742453,20,0,5,5
27,10,MDG_DM,"[-2.8722, -3.3393, 13.0472, 3.1363, -11.5981]",False,18.275173,20,2296,2316,0
28,10,MDG_Wolfe,"[-0.0027, 0.0015, -4.9746, -4.9734, -2.9857]",False,7.641720,20,863,50,0
29,10,Newton,"[-0.995, -2.9849, -4.9747, -4.9747, -2.9849]",False,8.264610,20,0,8,8
30,11,MDG_DM,"[-3.1289, -10.8242, -2.9914, 1.6098, 2.5883]",False,12.049590,20,2176,2196,0
31,11,MDG_Wolfe,"[0.9951, 0.0002, 3.9796, -3.9798, -1.9901]",False,6.052015,20,745,49,0
32,11,Newton,"[0.995, 0.0, 3.9798, -4.9747, -1.5076]",False,6.621870,20,0,5,5
33,12,MDG_DM,"[10.8355, 11.543, 2.5607, -3.9923, 0.0019]",False,16.527075,20,2680,2700,0
34,12,MDG_Wolfe,"[0.9942, -0.0003, 2.9843, -2.9856, -1.9896]",False,4.771487,20,682,54,0
35,12,Newton,"[1.5076, 3.9798, -2.5127, -2.5127, -0.0]",False,5.544314,20,0,6,6
36,13,MDG_DM,"[-2.5179, -12.4314, -5.1968, -6.3533, -8.017]",False,17.103324,20,2040,2060,0
37,13,MDG_Wolfe,"[2.982, 0.9959, 0.9954, -0.9961, 0.9919]",False,3.584810,20,601,59,0
38,13,Newton,"[5.9696, 3.9798, 4.9747, -3.5179, -2.5127]",False,9.742240,20,0,6,6
39,14,MDG_DM,"[8.3572, 2.8396, 10.7842, -2.0057, 0.811]",False,14.102679,20,2232,2252,0
40,14,MDG_Wolfe,"[-0.0054, 0.9951, -2.981, -1.9854, -1.9888]",False,4.215842,20,746,47,0
41,14,Newton,"[6.5333, -1.5076, -4.9747, -2.9849, -1.5076]",False,8.993744,20,0,8,8
42,15,MDG_DM,"[1.4784, 6.1544, -27.4288, -1.3489, -4.084]",False,28.476285,20,2536,2556,0
43,15,MDG_Wolfe,"[0.9933, 1.9888, 0.9916, 0.998, 1.9859]",False,3.296228,20,800,47,0
44,15,Newton,"[0.995, 2.9849, -2.5127, -1.9899, -0.995]",False,4.600313,20,0,6,6

,Método,Llegó al óptimo,Mejor dist,Mejor x_optimo,Avg f_invok,Avg Df_invok,Avg H_invok
0,MDG_DM,0/15,—,None,2286.93,2306.93,0.0
1,MDG_Wolfe,0/15,—,None,759.67,52.20,0.0
2,Newton,0/15,—,None,0.00,5.80,5.8